### ISSUE TITLE
don't work

### ISSUE THREAD

**Issue by ESSch** [igrigorik/autoperf#7]
Hello. I get a error:
```
root@kubernetes-master:/autoperf# ruby autoperf.rb -c replay_sample.conf 
Traceback (most recent call last):
        2: from autoperf.rb:8:in `<main>'
        1: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- ruport (LoadError)
root@kubernetes-master:/autoperf# ruby autoperf.rb -c requests_sample.conf 
Traceback (most recent call last):
        2: from autoperf.rb:8:in `<main>'
        1: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- ruport (LoadError)
```

**Comment by igrigorik** [comment]
Looks like you're missing a required gem... `gem install ruport`
